# Site settings
title: 陈三
email: chenxsan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  just another static blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: chenxsan
github_username:  chenxsan
excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 3
